<?php include('includes/header.php'); ?>

<div class="page-container">
    <?php include("includes/sidebar.php"); ?>

    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <h3 class="page-title">Codes</h3>

            <!-- BEGIN PAGE HEADER-->
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="<?php echo site_url('/admin/codes/all'); ?>">Codes</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Codes All</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->

            <!-- BEGIN PAGE CONTENT-->
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="icon-grid"></i>Codes All
                            </div>
                            <div class="actions">
                                <a href="<?php echo site_url('admin/codes/generate');?>" class="btn default yellow-stripe">
                                <i class="fa fa-plus"></i>
                                <span class="hidden-480">
                                    Generate Codes
                                </span>
                                </a>                               
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php include('includes/notes.php'); ?>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet-body">
                        <div class="table-container">
                            <table class="table table-striped table-bordered table-hover" id="datatable_admins">
                            <thead>
                            <tr role="row" class="heading">
                                <th width="10%">Purchase Number</th>
                                <th width="10%">Code</th>
                                <th width="8%">Code Type</th>
                                <th width="10%">Generated By</th>
                                <th width="10%">Purchased By</th>
                                <th width="10%">Used By</th>
                                <th width="10%">Used To</th>
                                <th width="10%">Date Purchased</th>
                                <th width="10%">Date Used</th>
                                <th width="10%">Status</th>
                                <th width="15%">
                                     Actions
                                </th>
                            </tr>
                            <tr role="row" class="filter">
                                <td>
                                    <input type="text" class="form-control form-filter input-sm" name="filter[both][purchase_no]">
                                </td>                                
                                <td>
                                    <input type="text" class="form-control form-filter input-sm" name="filter[both][code]">
                                </td>
                                <td>
                                    <select name="filter[both][type_id]" class="form-control form-filter input-sm">
                                        <option value=""></option>
                                        <option value="0">CD</option>
                                        <option value="1">Paid</option>
                                    </select>
                                </td>
                                <td>
                                    <input type="text" class="form-control form-filter input-sm" name="filter[both][generated_by]">
                                </td>                                                          
                                <td>
                                    <input type="text" class="form-control form-filter input-sm" name="filter[both][purchased_by]">
                                </td>
                                <td>
                                    <input type="text" class="form-control form-filter input-sm" name="filter[both][used_by]">
                                </td>                                                          
                                <td></td>                                                          
                                <td></td>                                                     
                                <td></td>                                                          
                                <td>
                                    <select name="filter[both][status]" class="form-control form-filter input-sm">
                                        <option value=""></option>
                                        <option value="0">Available</option>
                                        <option value="1">Used</option>
                                    </select>
                                </td>                                                       
                                <td>
                                    <div class="margin-bottom-5">
                                        <button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
                                        <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>
                                    </div>
                                </td>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>            
            <!-- END PAGE CONTENT-->
        </div>
    </div>
</div>

<?php include('includes/footer.php'); ?>
<div class="modal fade" id="cancel" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id='cancel-type'>Warning!</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="text-left" id="cancel-msg">Are you sure you want to cancel this code?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default blue" data-dismiss="modal" id="cancel-yes">Yes</button>
        <button type="button" class="btn btn-default red" data-dismiss="modal" id="cancel-no">No</button>
        <input type="hidden" id="input-code-id" value="">
      </div>      
    </div>
  </div>
</div>
<script>
var base_url = '<?php echo site_url(); ?>';

function cancelCode(code_id){
    $('#cancel').modal('show');
    $('#input-code-id').val(code_id);
}

$("#cancel-yes").on('click', function (){

    // var head_id = $('#wallet-move-button').data('head_id');
    var input_code_id = $('#input-code-id').val();
    var code_id = $('#cancel-code-button-'+input_code_id).data('code-id');
    
    $.ajax({//transactions/move-to-wallet/
        url: base_url+"admin/codes/ajax/remove-code",
        data:{'code_id' : code_id},
        success: function(data) {           
            if(data.status == 'success'){
                window.location.href = base_url+'admin/codes/listings/';
            }                
        },
        type: 'POST',
    });

});


var Codes = function () {

    var handleCodes = function () {

        var grid = new Datatable();

        grid.init({
            src: $("#datatable_admins"),
            onSuccess: function (grid) {
                // execute some code on network or other general error  
            },
            onError: function (grid) {
                // execute some code on network or other general error  
            },
            loadingMessage: 'Loading...',
            dataTable: { // here you can define a typical datatable settings from http://datatables.net/usage/options 
                // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/scripts/datatable.js). 
                // So when dropdowns used the scrollable div should be removed. 
                //"dom": "<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'<'table-group-actions pull-right'>>r>t<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'>>",

                "lengthMenu": [
                    [10, 20, 50, 100, 150],
                    [10, 20, 50, 100, 150] // change per page values here
                ],
                "pageLength": 10, // default record count per page
                "ajax": {
                    "url": base_url + 'admin/codes/ajax/get_all_codes', // ajax source
                },
                "order": [
                    [0, "desc"]
                ] // set first column as a default sort by asc
            }
        });
    }

    return {
        //main function to initiate the module
        init: function () {
            handleCodes();
        }
    };
}();

jQuery(document).ready(function() {
    Codes.init()
});
</script>